---
title: "Lab 3: Class Survey"
author: "STAT 20 Spring 2022"
output: pdf_document
---

## Part I: Understanding the Context of the Data

1. What is the unit of observation in the class survey?

2. Where in the Taxonomy of Data are the variables that correspond to each of the following survey questions (i.e., what is their type)?
  - Question 6: What is your favorite thing about Cal?
  - Question 13: Where would you rather be?
  - Question 20: What is the chance that we remain in remote learning for the entire semester?

3. What values would you expect `major` to take? Do you anticipate any challenges when analyzing this data?

To lay the groundwork for your analysis on the survey data set, you will make a plan for constructing plots and set your expectations for what you will see. For questions 4 - 7, please:

- sketch (with paper and pencil) a plot that captures the distribution or relationship between the variables,
- label the axis and add axis tick marks with plausible values,
- depict a shape that reflects your expectation of the phenomena. Also:
- indicate the *aesthetic mappings* (the variables in use and which visual cues / aeshetic each one is mapped to) and
- indicate the *geometry* of your plot.
  
4. Do students prefer to spend time at the beach or in the mountains?

5. How much coding experience do students have, ranked from 1 - 10?

6. What are students' perceptions of the chance that we remain in remote learning for the entire semester?

7. What is the relationship between students optimism for cryptocurrency and their skepticism of the effect of technology on interpersonal relationships?


## Part II: Computing on the Data

1. What is the relationship between year (first year vs second/third/fourth year) and favorite boba place?

1. What is the relationship between favorite season and preference for beach or mountains? 

1. Among those who have had previous coding experience, what languages are most common? Do the proportions of languages used differ by major?

1. Which boba place is the most popular among students who prefer tea over coffee?

1. We are back on campus starting Jan 31. Based on the survey, do you think most students expected this outcome? Why? 

1. Among students whose favorite season is winter, which Winter Olympic sport do they enjoy the most? Which do they enjoy the least? Justify your answer with visualization.

1. Group the students based on whether they believe hotdogs are sandwiches. What proportion of each group prefer fighting a horse-sized duck? Do you think the two questions are associated?

1. How many second-year students gave an opinion of 7 or above to the Cryptocurrency statement?

1. What is the relationship between major (Health/Pre-Med and non Health/Pre-Med) and degree of belief that COVID will keep us remote for two weeks plus?

2. 
## Part III: Extensions


