---
title: 'Lab 7B: Hypothesis Testing'
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE, 
                      echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

## Part I: Permutation Tests

We've gone through several examples of hypothesis tests in lecture and in the lab activity. Now you'll get the chance to get your hands on the data and construct those tests using the computational approach to finding the null distribution. All of the data sets for this lab can be found in the `stats20data` package. Parts a, d, and h require written English answers; the other parts can be answered just with code, output, and plots.

1. Using the `yawn` data set,
    a. Write the null and alternative hypothesis.
    b. Compute the observed test statistic.
    c. Visualize the observed data using an appropriate plot.
    d. Construct a plot featuring 9 subplots, each one featuring a visualization of a data set generated under the null hypothesis. Does your visualization of the observed data from the previous part look like it be one of these plots?
    e. Construct and save the null distribution of statistics.
    f. Visualize the null distribution.
    g. Compute the p-value.
    h. Interpret the p-value. What does it say about the consistency between the null hypothesis and the observed data?

2. Using the `promote` data set,
    a. Write the null and alternative hypothesis.
    b. Compute the observed test statistic.
    c. Visualize the observed data using an appropriate plot.
    d. Construct a plot featuring 9 subplots, each one featuring a visualization of a data set generated under the null hypothesis. Does your visualization of the observed data from the previous part look like it be one of these plots?
    e. Construct and save the null distribution of statistics.
    f. Visualize the null distribution.
    g. Compute the p-value.
    h. Interpret the p-value. What does it say about the consistency between the null hypothesis and the observed data?
    

## Part II: Tests with a Point Null

3. Using the `millennials` data set (discussed in lecture 3/5)
    a. Write the null and alternative hypothesis.
    b. Compute the observed test statistic.
    c. Visualize the observed data using an appropriate plot.
    d. Construct a plot featuring 9 subplots, each one featuring a visualization of a data set generated under the null hypothesis. Does your visualization of the observed data from the previous part look like it be one of these plots?
    e. Construct and save the null distribution of statistics.
    f. Visualize the null distribution.
    g. Compute the p-value.
    h. Interpret the p-value. What does it say about the consistency between the null hypothesis and the observed data?

4. In the 2016 NBA season, it was noted that professional basketball player Steph Curry had a remarkable basket-shooting performance beyond 30 feet. The `curry` data frame contains his long range shooting performance across 27 attempts. By comparison, the long range shooting percentage of NBA players that season was 7.5%. Assess whether this data is consistent with the notion that Steph Curry has a long range shooting percentage that is no different from the average NBA player. Said another way, assess just how remarkable this Curry's shooting performance was in 2016.
    a. Write the null and alternative hypothesis.
    b. Compute the observed test statistic.
    c. Visualize the observed data using an appropriate plot.
    d. Construct a plot featuring 9 subplots, each one featuring a visualization of a data set generated under the null hypothesis. Does your visualization of the observed data from the previous part look like it be one of these plots?
    e. Construct and save the null distribution of statistics.
    f. Visualize the null distribution.
    g. Compute the p-value.
    h. Interpret the p-value. What does it say about the consistency between the null hypothesis and the observed data?
  